import uuid
from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    Text,
    false,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.types import str_enum


class RemotePreference(StrEnum):
    ONSITE = "onsite"
    HYBRID = "hybrid"
    REMOTE = "remote"
    ANY = "any"


class Resume(Base):
    """An uploaded resume. Its extracted text is the candidate evidence source of truth."""

    __tablename__ = "resumes"
    __table_args__ = (
        # At most one primary resume.
        Index(
            "uq_resumes_single_primary",
            "is_primary",
            unique=True,
            postgresql_where=text("is_primary"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(Text)
    original_filename: Mapped[str] = mapped_column(Text)  # sanitized, display only
    # Storage key generated by the server (never a user-supplied path).
    file_path: Mapped[str] = mapped_column(Text, unique=True)
    mime_type: Mapped[str] = mapped_column(Text)
    size_bytes: Mapped[int] = mapped_column(BigInteger)

    raw_text: Mapped[str] = mapped_column(Text)  # normalized extracted text
    text_hash: Mapped[str] = mapped_column(Text, index=True)  # sha256 of raw_text

    is_primary: Mapped[bool] = mapped_column(Boolean, default=False, server_default=false())

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    @property
    def text_chars(self) -> int:
        return len(self.raw_text)

    profile: Mapped["CandidateProfile"] = relationship(
        back_populates="resume", cascade="all, delete-orphan", uselist=False, lazy="selectin"
    )


class CandidateProfile(Base):
    """User-entered structured profile for one resume (PRD §14; manual entry in P2)."""

    __tablename__ = "candidate_profiles"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    resume_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("resumes.id", ondelete="CASCADE"), unique=True
    )

    target_roles: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    skills: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    years_experience: Mapped[Decimal | None] = mapped_column(Numeric(4, 1))
    industries: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    education: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    certifications: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    # [{"language": "English", "level": "C2"}, ...]
    languages: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, default=list, server_default="[]"
    )
    preferred_locations: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")
    remote_preference: Mapped[RemotePreference | None] = mapped_column(
        str_enum(RemotePreference, "remote_preference")
    )
    work_authorization: Mapped[list[str]] = mapped_column(JSONB, default=list, server_default="[]")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    resume: Mapped[Resume] = relationship(back_populates="profile")
