"""StorageProvider boundary (PRD §73) and the local-disk implementation.

Files live under UPLOAD_DIR, outside any web-served directory. Keys are generated by the
server; user-supplied names never become paths.
"""

import os
import secrets
import tempfile
from pathlib import Path
from typing import Protocol


class StorageError(Exception):
    pass


class StorageProvider(Protocol):
    def save(self, data: bytes, *, folder: str, suffix: str) -> str: ...

    def read(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...


class LocalStorageProvider:
    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root) or path == self.root:
            raise StorageError("Invalid storage key")
        return path

    def save(self, data: bytes, *, folder: str, suffix: str) -> str:
        if not folder.isidentifier() or (suffix and not suffix[1:].isalnum()):
            raise StorageError("Invalid folder or suffix")
        key = f"{folder}/{secrets.token_hex(16)}{suffix}"
        path = self._path(key)
        path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        # Write atomically with owner-only permissions.
        fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".upload-")
        try:
            with os.fdopen(fd, "wb") as handle:
                handle.write(data)
            os.chmod(tmp, 0o600)
            os.replace(tmp, path)
        except BaseException:
            Path(tmp).unlink(missing_ok=True)
            raise
        return key

    def read(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)
